fix/events not properly tracked
limitless-labs-group/Limitless-Exchange pull request #5
Opened 2024-04-05 09:17 UTC by carlomigueldy

- feat: add track click create own market button
- fix: func args for trackCopied
- refactor: disable default pageViews and refactor track func emitters & added debug logs
- feat: track create new market clicked btn event
- feat: track profile burger menu
- feat: add more events as defined from taxonomy page
- feat: add missing track share click event
- refactor: rename property as per definition from taxonomy doc

2024-04-08 12:56 UTC, maxschnaider approved these changes

2024-04-09 04:23 UTC, carlomigueldy commented
I removed the version tag, now pull request is ready for review

2024-04-09 07:22 UTC, maxschnaider requested changes

2024-04-09 07:22 UTC, maxschnaider commented on src/components/markets/CreateMarketCard.tsx
>          </Button>
@carlomigueldy pls take note I've added onClick event into the whole parent container, this button is just for UI, so there's a chance the user clicks let's say on the header and will be redirected without the event being tracked

2024-04-09 07:22 UTC, maxschnaider commented on src/components/layouts/Header.tsx
> +                    })
how sustainable is this approach, in case we will have tens of pages? maybe explore to use `page: pathname`?

2024-04-10 18:08 UTC, merged